# Programación Numérica a través de la librería NumPy.
___

## Ejercicio 1
Crea una función que dado un Array de una dimensión, te haga un resumen estadístico básico de los datos. Si detecta que el array tiene más de una dimensión, debe mostrar un mensaje de error.



In [1]:
import numpy as np #importa la libreria numpy

Se define la funcion que contendra las operaciones estadisticas basicas para calcular en un 'array' dado por el usuario, 
- Siempre y cuando tenga una sola dimension, para lo cual se genera un condicional if, y si se cumple con la condicion se generara el resumen. 
- Entre los calculos se han incluido: la media, la mediana, el minimo, el maximo, la desviacion estandar y la varianza de los datos. 
- Finalmente se da la instruccion de imprimir el resumen.
- Si el array tiene mas de una dimension se imprimira un mensaje expresando que el formato es incorrecto.

In [14]:
def statistic(array): #definicion de la funcion
    if array.ndim ==1: #cndicional a 1 dimension
        mean = np.mean(array)
        median = np.median(array)
        min = np.amin(array)
        max = np.amax(array)
        
        std = round(np.std(array), 2) #se redondea para tener solo 2 decimales
        variance = np.var(array)

        statistic_resume = "El resumen estadistico del conjunto de datos es:\n Media es {},\n Mediana es {},\n Minimo es {},\n Maximo es {},\n Desviacion estandar es {},\n Varianza es {}"
        print(statistic_resume.format(mean,median,min,max,std,variance))
    else:
        print('Error: el array no es correcto')

Ahora, se prueba la condicion en un array de una dimension, primero generando el array y espues llamando a la funcion:

In [15]:
array_n1 = np.array([10,15,20,25,8,12,16,24]) #genera array
statistic(array_n1) #llama a la funcion con el parametro de entrada del array creado

El resumen estadistico del conjunto de datos es:
 Media es 16.25,
 Mediana es 15.5,
 Minimo es 8,
 Maximo es 25,
 Desviacion estandar es 5.89,
 Varianza es 34.6875


El array tiene una sola dimension, lo que cumple el condicional y, por lo tanto, se genera el resumen estadistico.

In [17]:
array_n2= np.array([[1,2,3],[4,5,6]]) #se genera el array
statistic(array_n2) #se llama a la funcion

Error: el array no es correcto


Se prueba una vez mas la funcion en un array de dos dimensiones, y se puede observar el error generado que fue definido dentro de la funcion 

## Ejercicio 2
Crea una función que genere un cuadrado NxN de números aleatorios entre el 0 y el 100.



Se define la funcion que toma como parametros dos numeros que indicaran la forma de la matriz, dentro de la funcion con se utiliza la funcion random y se especifica que el numero maximo es de 100 y la forma que tendra el array.

In [20]:
def arr_random(x,y): #se define la funcion que requiere dos parametros para la forma
    np.random.randint(100, size=(x, y)) #genera array 
    print(array)

Se utiliza la funcion indicando los parametros de la forma, en este caso cuadrada, y se llama a la funcion para generar el array.

In [22]:
x = 5
y = 5
arr_random(x,y) #se llama a la funcion

[[84 63 79  3 52]
 [20 42 18 33 62]
 [67  3 45 34 22]
 [63  5 32 87 47]
 [99 11 16 96 66]]


## Ejercicio 3
Crea una función que dada una tabla de dos dimensiones, te calcule los totales por fila y los totales por columna.



Se genera la funcion que toma como parametro un array dado, dentro de la funcion se genera un condicional para comprobar que el array tenga dos dimensiones y se utiliza la funcion suma para generar la suma de las columnas y de las filas y se imprimen.

In [31]:
def totales (array): #definicion de funcion
    if array.ndim ==2: #condicional
        print("Suma de las columnas): ", np.sum(array, axis = 0)) #suma de columnas
        print("Suma de las filas: ", np.sum(array, axis = 1)) #suma de filas

Se genera un array y se llama a la funcion creada:

In [32]:
array_2d = np.random.randint(50, size=(2,5)) #genera array con numeros aleatorios
print(array_2d) #imprime array para ver los numeros generados
totales(array_2d) #se llama a la funcion que imprime los totales

[[34 42 19 14 34]
 [33 10 26  7  1]]
Suma de las columnas):  [67 52 45 21 35]
Suma de las filas:  [143  77]


## Ejercicio 4
Implementa manualmente una función que calcule el coeficiente de correlación. Infórmate sobre sus usos e interpretación.

El coeficiente de correlacion es una ecuacion estadistica que se usa para determinar el grado de fuerza entre la relacion lineal de dos variables. Es decir, mediante su analisis se puede interpretar si una variable tiene relacion con otra, por ejemplo si cambian los valores de *'x'* tambien cambiaran los valores de *'y'*. 

In [33]:
import math #importamos el paquete de math

Se define una funcion que contiene la formula de calculo del coeficiente de correlacion de pearson

In [51]:
def coef_correlation(X, Y, n) :
    sum_X = 0
    sum_Y = 0
    sum_XY = 0
    squareSum_X = 0
    squareSum_Y = 0
      
    #iteracion en los elementos del array para sumar cada uno dentro de una variable, despues sumar ambos array y 
    #por ultimo calcular el cuadrado de la suma
    i = 0
    while i < n :
        # suma de elementos en array X.
        sum_X = sum_X + X[i]
          
        # suma de los elementos en array Y.
        sum_Y = sum_Y + Y[i]
          
        # suma de X[i] * Y[i].
        sum_XY = sum_XY + X[i] * Y[i]
          
        # suma del cuadrado de los elementos del array
        squareSum_X = squareSum_X + X[i] * X[i]
        squareSum_Y = squareSum_Y + Y[i] * Y[i]
          
        i = i + 1
       
    # formula para calcular la correlacion:
    corr = (float)(n * sum_XY - sum_X * sum_Y)/((float)(math.sqrt((n * squareSum_X - sum_X * sum_X)* (n * squareSum_Y - sum_Y * sum_Y))))
    return corr

In [63]:
X = np.random.rand(7) #crea un array de numeros hasta el 7
Y = np.random.rand(7) #crea un array de numeros hasta el 7
print(X,'\n', Y)

#calcular longitud del array
n = len(X)
  
# Llamado a la funcion de calculo para la correlacion (con 3 decimales): 
print ('El coeficiende de correlacion es:''{0:.3f}'.format(coef_correlation(X, Y, n)))

[0.59670183 0.4377197  0.87511156 0.61627581 0.73517649 0.91855213
 0.06120893] 
 [0.90188849 0.15881538 0.8196785  0.84133614 0.22926473 0.55667429
 0.08355668]
El coeficiende de correlacion es:0.571


Del resultado obtenido, se puede observar que entre el conjunto de valores tenemos una correlacion positiva y moderada entre ellos.

- Cuando una correlacion es mayor que *'0'*, se considera positiva. Entre mas cercano sea el coeficiente a 1, mayor es la relacion entre las variables, siendo 1 una relación lineal positiva perfecta. 
- Por el contrario, si es menor que *'0'* indica que la correlacion es negativa, osea que se asocian en sentido inverso (cuando el valor en una sea muy alto, el valor en la otra será muy bajo). si el valor es exactamente -1, significa que es correlación negativa perfecta.
- Cuando el valor es igual que *'0'* significa que no existe relacion entre las variables.